# Site settings
title: mez.im
email: contact@mez.im
description: >
  Well, this is awkward.  I don't really have a description.
  But I do have a bag of candy.<br />Would you like one?  No?
  Oh well, more for me.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mez.im" # the base hostname & protocol for your site
twitter_username: mezzle
github_username:  mezzle

# Build settings
markdown: kramdown
exclude:
 - unicorn.rb
 - README.md
 - Procfile
 - Gemfile
 - Gemfile.lock
 - config.ru
 - vendor
 - app.json
